version: "3.7"

services:

  client:
    build: ./client
    image: htwimimap/client:latest
    ports:
      - "3000:80"
    environment:
      - API_HOST=${API_HOST}

  server:
    build: ./server
    image: htwimimap/server:latest
    ports:
      - "9000:9000"
    depends_on:
      - db
    environment:
      - NODE_ENV=${NODE_ENV}
      - LDAP_URL=${LDAP_URL}
      - LDAP_SEARCH_BASE=${LDAP_SEARCH_BASE}
      - LDAP_STUDENT_GROUP=${LDAP_STUDENT_GROUP}
      - LDAP_INSTRUCTOR_GROUP=${LDAP_INSTRUCTOR_GROUP}
      - AUTH_SECRET=${AUTH_SECRET}
      - BYPASS_LDAP=${BYPASS_LDAP}
      - API_HOST=${API_HOST}

  db:
    image: mongo:bionic
    volumes:
      - db-data:/data/db

  db-gui:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_USER}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_PASS}

volumes:
  db-data:
