version: "3.7"

services:

  client:
    build: ./client
    image: imimap21/client:latest
    ports:
      - "80:80"

  server:
    build: ./server
    image: imimap21/server:latest
    ports:
      - "9000:9000"
    depends_on:
      - db

  db:
    image: mongo:bionic
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db

  db-gui:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=db

volumes:
  db-data:
