version: "3.7"

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/ssl:/etc/nginx/certs
      
  client:
    build: ./client
    image: htwimimap/client:latest
    ports:
      - "3000:80"
    environment:
      - API_HOST=${API_HOST}
      - VIRTUAL_HOST=imi-map-staging.f4.htw-berlin.de
      - VIRTUAL_PORT=8080
      
  server:
    build: ./server
    image: htwimimap/server:latest
    ports:
      - "9000:9000"
    depends_on:
      - db
    environment:
      - NODE_ENV=${NODE_ENV}
      - LDAP_URL=${LDAP_URL}
      - LDAP_SEARCH_BASE=${LDAP_SEARCH_BASE}
      - LDAP_STUDENT_GROUP=${LDAP_STUDENT_GROUP}
      - LDAP_INSTRUCTOR_GROUP=${LDAP_INSTRUCTOR_GROUP}
      - AUTH_SECRET=${AUTH_SECRET}
      - REFRESH_SECRET=${REFRESH_SECRET}
      - BYPASS_LDAP=${BYPASS_LDAP}
      - API_HOST=${API_HOST}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    networks:
      - backend
    volumes:
      - pdf-store:/server/pdfs

  db:
    image: mongo:bionic
    volumes:
      - db-data:/data/db
    networks:
      - backend

  db-gui:
    image: mongo-express
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_USER}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_PASS}
    networks:
      - backend

volumes:
  db-data:
  pdf-store:

networks:
  backend:
