version: '3'
services:
  vue-client:
    container_name: "im2-client"
    build: ./client
    command: bash -c "npm install && npm run serve"
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "8080:8080"

  mongo:
    container_name: "im2-db"
    image: library/mongo:4.2-bionic
    volumes:
      - ./tmp/data:/data/db
    ports:
      - "27017:27017"

  node-server:
    container_name: "im2-server"
    build: ./server
    command: bash -c "npm install && npm run serve"
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - "9000:9000"