version: "3.7"

services:

  client:
    build:
      target: dev
    ports:
    - "8080:8080"
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VIRTUAL_PORT=8080

  server:
    build:
      target: dev
    ports:
      - "9229:9229"
    volumes:
      - /app/node_modules
      - ./server:/app
