version: "3.7"

services:

  client:
    build: ./client
    image: htwimimap/client:latest
    ports:
      - "80:80"

  server:
    build: ./server
    image: htwimimap/server:latest
    ports:
      - "9000:9000"
    depends_on:
      - db

  db:
    image: mongo:bionic
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}

  db-gui:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASS}
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_USER}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_PASS}

volumes:
  db-data:
